spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      
      mvc:
        routes:
        -  id: products
           uri: lb://PRODUCT-MS
           predicates:
             - Path=/api/products/**
        -  id: orders
           uri: lb://ORDER-MS
           predicates:
             - Path=/api/orders/**     
              
             
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
  timelimiter:
    configs:
      default:
        timeout-duration: 5s                   
             
           
             
                
                          
            
             